-- Simple PostgreSQL initialization script
-- This runs in the context of the eshopdb database

-- Create required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Create schemas
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS basket;
CREATE SCHEMA IF NOT EXISTS ordering;
CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS messaging;

-- The eshopuser already exists and has permissions from POSTGRES_USER
-- Grant schema usage permissions
GRANT USAGE ON SCHEMA catalog TO eshopuser;
GRANT USAGE ON SCHEMA basket TO eshopuser;
GRANT USAGE ON SCHEMA ordering TO eshopuser;
GRANT USAGE ON SCHEMA identity TO eshopuser;
GRANT USAGE ON SCHEMA shared TO eshopuser;
GRANT USAGE ON SCHEMA messaging TO eshopuser;

-- Grant all privileges on schemas
GRANT ALL PRIVILEGES ON SCHEMA catalog TO eshopuser;
GRANT ALL PRIVILEGES ON SCHEMA basket TO eshopuser;
GRANT ALL PRIVILEGES ON SCHEMA ordering TO eshopuser;
GRANT ALL PRIVILEGES ON SCHEMA identity TO eshopuser;
GRANT ALL PRIVILEGES ON SCHEMA shared TO eshopuser;
GRANT ALL PRIVILEGES ON SCHEMA messaging TO eshopuser;

-- Grant default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT ALL ON TABLES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA basket GRANT ALL ON TABLES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA ordering GRANT ALL ON TABLES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL ON TABLES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared GRANT ALL ON TABLES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA messaging GRANT ALL ON TABLES TO eshopuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT ALL ON SEQUENCES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA basket GRANT ALL ON SEQUENCES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA ordering GRANT ALL ON SEQUENCES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL ON SEQUENCES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared GRANT ALL ON SEQUENCES TO eshopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA messaging GRANT ALL ON SEQUENCES TO eshopuser;