services:
  postgres:
    environment:
      POSTGRES_DB: eshopdb_prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    restart: unless-stopped

  rabbitmq:
    restart: unless-stopped

  keycloak:
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/eshopdb_prod
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTP_ENABLED: false
      KC_HTTPS_ENABLED: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  seq:
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+:8081;http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eshopdb_prod;Username=eshopuser;Password=EShop123!;SearchPath=shared,public;Include Error Detail=true"
      ConnectionStrings__CatalogConnection: "Host=postgres;Port=5432;Database=eshopdb_prod;Username=eshopuser;Password=EShop123!;SearchPath=catalog,shared,public;Include Error Detail=true"
      ConnectionStrings__BasketConnection: "Host=postgres;Port=5432;Database=eshopdb_prod;Username=eshopuser;Password=EShop123!;SearchPath=basket,shared,public;Include Error Detail=true"
      ConnectionStrings__OrderingConnection: "Host=postgres;Port=5432;Database=eshopdb_prod;Username=eshopuser;Password=EShop123!;SearchPath=ordering,shared,public;Include Error Detail=true"
      ConnectionStrings__IdentityConnection: "Host=postgres;Port=5432;Database=eshopdb_prod;Username=eshopuser;Password=EShop123!;SearchPath=identity,public;Include Error Detail=true"
      # Production logging
      Logging__LogLevel__Default: Warning
      Logging__LogLevel__Microsoft: Error
      Logging__LogLevel__System: Error
      # Seq logging
      Seq__ServerUrl: "http://seq:80"
      Seq__MinimumLevel: Warning
    restart: unless-stopped
    ports:
      - "443:8081"
      - "80:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_prod_data: